Изменил выгрузку и загрузку реквизитов с типом "ХранилищеЗначения"
xDrivenDevelopment/xUnitFor1C pull request #771
Opened 2017-12-15 00:19 UTC by Andrewww123

Изменил выгрузку и загрузку реквизитов с типом "ХранилищеЗначения", добавил сериализацию и десериализацию

2017-12-15 07:58 UTC, artbear commented
Добавь еще выгрузку на исходники через precommit1c.
Чтобы было понятно, что же поменялось.
И не нужно было принимать кота в мешке :)

2017-12-17 23:27 UTC, Andrewww123 commented
Это нужно заново форк сделать и закоммитить еще раз изменения?

2017-12-18 08:01 UTC, artbear commented
Нет, нужно установить прекоммит1с для твоего локального репозитория.
Исправить внешнюю обработку Сериализатор, добавь ее в индекс гита и сделать еще раз коммит в свою же ветку, исходную для данного ПР.
Если все сделано правильно, то в коммите появятся доп.файлы, а не только один epf-файл.
И тогда делаешь пуш, и в этот же PR прилетает твой коммит.

2017-12-18 10:38 UTC, Andrewww123 commented
Понял.. Тогда дубль-2

2017-12-18 15:04 UTC, artbear commented
Ага, так лучше.
Видны исправления.

2017-12-18 15:06 UTC, artbear requested changes

2017-12-18 15:06 UTC, artbear commented on src/Plugins/СериализаторMXL/ObjectModule.bsl
> +				Значение = XMLЗначение(Тип("ХранилищеЗначения"), стрПоле.Значение);
Так может поломаться совместимость.
Если я не ошибаюсь, в старых макетах подобное поле заполнялось просто строкой "ХранилищеЗначения".
В этом случае при загрузке подобных макетов и выполнении твоего кода `Значение = XMLЗначение(Тип("ХранилищеЗначения"), стрПоле.Значение);`
будет неверное преобразование строки в неверное хранилище.

Или я ошибаюсь?

2017-12-18 21:51 UTC, Andrewww123 commented on src/Plugins/СериализаторMXL/ObjectModule.bsl
> +				Значение = XMLЗначение(Тип("ХранилищеЗначения"), стрПоле.Значение);
Не ошибаешься, так и есть. Ладно, подумаю как выкрутиться

2017-12-20 02:19 UTC, Andrewww123 commented
Добавил условие чтобы строка "ХранилищеЗначения" обрабатывалась по-старому

2017-12-20 08:14 UTC, artbear approved these changes

2017-12-20 08:14 UTC, merged

2017-12-20 08:14 UTC, artbear commented
@Andrewww123 Спасибо за PR